name: CI/CD_demo

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:                  # what to do
  test:
    runs-on: ubuntu-latest    # which machine
    steps:                    # sequence of commands
      - name: checkout code
        uses: actions/checkout@v4 
      - name: setup python
        uses: actions/setup-python@v4
        with:
         python-version: '3.11'
        # Install dependencies
      - run: pip install -r requirements.txt

      # Install Playwright
      - run: playwright install chromium

      # Run tests
      - run: pytest -m smoke -v
